<<<<<<< HEAD
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
wheat_thins = Item.create(name: "Wheat Thins", category: "Snacks", img_url: "https://i.imgur.com/a1cLXfi.jpg", price: 3.44)
tostitos = Item.create(name: "Tostitos", category: "Snacks", img_url: "https://i.imgur.com/0ZOjTo7.jpg", price: 3.98)
original_ruffles = Item.create(name: "Ruffles - Original", category: "Snacks", img_url: "https://i.imgur.com/LKR5YUP.jpg", price: 3.98)
ritz_crackers = Item.create(name: "Ritz", category: "Snacks", img_url: "https://i.imgur.com/9xbEfyH.jpg", price: 2.68)
oreo = Item.create(name: "Oreo", category: "Snacks", img_url: "https://i.imgur.com/9FQbVag.jpg", price: 2.96)
fritos = Item.create(name: "Fritos", category: "Snacks", img_url: "https://i.imgur.com/AGzXmkR.jpg", price: 3.28)
red_bell_pepper = Item.create(name: "Red Bell Pepper", category: "Produce", img_url: "https://i.imgur.com/LWHra2y.jpg", price: 1.38)
doritos = Item.create(name: "Doritos", category: "Snacks", img_url: "https://i.imgur.com/T3siVrT.jpg", price: 3.98)
cheddar_ruffles = Item.create(name: "Ruffles - Cheddar & Sour Cream", category: "Snacks", img_url: "https://i.imgur.com/L7Uedyp.jpg", price: 2.98)
strawberries = Item.create(name: "Strawberries", category: "Produce", img_url: "https://i.imgur.com/w4Xrvlb.jpg", price: 3.39)
butter = Item.create(name: "Kerrygold Pure Irish Salted Butter", category: "Dairy", img_url: "https://i.imgur.com/dBrET2Q.jpg", price: 3.99)
potato = Item.create(name: "Russet Potato", category: "Produce", img_url: "https://i.imgur.com/kqW7iv9.jpg", price: 0.67)
grapes = Item.create(name: "Red Seedless Grapes", category: "Produce", img_url: "https://i.imgur.com/rLiFIb0.jpg", price: 5.98)
onion = Item.create(name: "Yellow Onion", category: "Produce", img_url: "https://i.imgur.com/2Dw70Gj.jpg", price: 0.72)
turkey = Item.create(name: "Sliced Honey Roasted Turkey", category: "Meat", img_url: "https://i.imgur.com/LmjReRu.jpg", price: 4.98)
apple = Item.create(name: "Gala Apple", category: "Produce", img_url: "https://i.imgur.com/ho4n8Fq.jpg", price: 1.35)
ham = Item.create(name: "Sliced Honey Ham", category: "Meat", img_url: "https://i.imgur.com/RV96f5R.jpg", price: 3.28)
ground_beef = Item.create(name: "80% Lean Ground Beef", category: "Meat", img_url: "https://i.imgur.com/cpHJjSs.jpg", price: 4.39)
chicken = Item.create(name: "Chicken Breast Fillets", category: "Meat", img_url: "https://i.imgur.com/gFTkiq1.jpg", price: 5.99)
hotdogs = Item.create(name: "Ball Park Franks", category: "Meat", img_url: "https://i.imgur.com/Qmxi42A.jpg", price: 3.49)
sourcream = Item.create(name: "Daisy Sour Cream", category: "Dairy", img_url: "https://i.imgur.com/yjiefhp.jpg", price: 1.77)
bacon = Item.create(name: "Hormel Bacon", category: "Meat", img_url: "https://i.imgur.com/cNPh8az.jpg", price: 5.00)
mozzarella = Item.create(name: "Shredded Mozzarella Cheese", category: "Dairy", img_url: "https://i.imgur.com/u0GdkoU.jpg", price: 5.99)
milk = Item.create(name: "Milk", category: "Dairy", img_url: "https://i.imgur.com/JdCvsTx.jpg", price: 4.49)
eggs = Item.create(name: "Eggs", category: "Dairy", img_url: "https://i.imgur.com/eO5FYqQ.jpg", price: 2.79)
cream_cheese = Item.create(name: "Philadelphia Original Cream Cheese", category: "Dairy", img_url: "https://i.imgur.com/dcYqZF6.jpg", price: 1.96)
mexican_cheese = Item.create(name: "Shredded Mexican Four Cheese Blend", category: "Dairy", img_url: "https://i.imgur.com/uqi8Jzi.jpg", price: 2.19)
almond_breeze = Item.create(name: "Almond Breeze Almondmilk", category: "Dairy", img_url: "https://i.imgur.com/1OgYyf8.jpg", price: 3.77)
sargento = Item.create(name: "Sargento Medium Cheddar Cheese Slices", category: "Dairy", img_url: "https://i.imgur.com/QrFc3Rc.jpg", price: 2.68)


=======
wheat_thins = Item.create(description: "Pair snack crackers with cheese and meat or enjoy by themselves.", name: "Wheat Thins", category: "Snacks", img_url: "https://i.imgur.com/a1cLXfi.jpg", price: 3.44)
tostitos = Item.create(description: "It's like a mini chip bowl in every bite.", name: "Tostitos Scoops", category: "Snacks", img_url: "https://i.imgur.com/0ZOjTo7.jpg", price: 3.98)
original_ruffles = Item.create(description: "Classic tasty flavor of RUFFLES Potato Chips.", name: "Ruffles - Original", category: "Snacks", img_url: "https://i.imgur.com/LKR5YUP.jpg", price: 3.98)
ritz_crackers = Item.create(description: "Flaky and delicious snack crackers with a rich, buttery flavor.", name: "Ritz", category: "Snacks", img_url: "https://i.imgur.com/9xbEfyH.jpg", price: 2.68)
oreo = Item.create(description: "Chocolate wafers stuffed with twice the OREO creme", name: "Oreo", category: "Snacks", img_url: "https://i.imgur.com/9FQbVag.jpg", price: 2.96)
fritos = Item.create(description: "FRITOS tasty corn chips are a delicious lunch or dinner snack.", name: "Fritos", category: "Snacks", img_url: "https://i.imgur.com/AGzXmkR.jpg", price: 3.28)
red_bell_pepper = Item.create(description: "Excellent Source of Vitamin C.", name: "Red Bell Pepper", category: "Produce", img_url: "https://i.imgur.com/LWHra2y.jpg", price: 1.38)
doritos = Item.create(description: "Tortilla chips flavored with delicious nacho cheese.", name: "Doritos", category: "Snacks", img_url: "https://i.imgur.com/T3siVrT.jpg", price: 3.98)
cheddar_ruffles = Item.create(description: "Cheddar Sour Cream is blend of rich, velvety cheddar with smooth, creamy sour cream flavor.", name: "Ruffles - Cheddar & Sour Cream", category: "Snacks", img_url: "https://i.imgur.com/L7Uedyp.jpg", price: 2.98)
strawberries = Item.create(description: "Wash before consuming, Add to a meals & desserts or on their own.", name: "Strawberries", category: "Produce", img_url: "https://i.imgur.com/w4Xrvlb.jpg", price: 3.39)
butter = Item.create(description: "European-style salted butter is made on family farms from the milk of grass-fed cows.", name: "Kerrygold Pure Irish Salted Butter", category: "Dairy", img_url: "https://i.imgur.com/dBrET2Q.jpg", price: 3.99)
potato = Item.create(description: " Along with rice and wheat, potatoes are one of most important staple crop, Russet potatoes are also a good source of minerals.", name: "Russet Potato", category: "Produce", img_url: "https://i.imgur.com/kqW7iv9.jpg", price: 0.67)
grapes = Item.create(description: "Grown in United States, Chile, or Mexico.", name: "Red Seedless Grapes", category: "Produce", img_url: "https://i.imgur.com/rLiFIb0.jpg", price: 5.98)
onion = Item.create(description: "Onions like to breathe, so keep them in a well-ventilated area like your pantry.", name: "Yellow Onion", category: "Produce", img_url: "https://i.imgur.com/2Dw70Gj.jpg", price: 0.72)
turkey = Item.create(description: "Made with slow cooked, oven roasted turkey sweetened with honey and no artificial flavors.", name: "Sliced Honey Roasted Turkey", category: "Meat", img_url: "https://i.imgur.com/LmjReRu.jpg", price: 4.98)
apple = Item.create(description: "Organic Fruit, Natural, Can be stored in refrigerators.", name: "Gala Apple", category: "Produce", img_url: "https://i.imgur.com/ho4n8Fq.jpg", price: 1.35)
ham = Item.create(description: "Made with slow cooked, oven roasted ham sweetened with honey and no artificial flavors.", name: "Sliced Honey Ham", category: "Meat", img_url: "https://i.imgur.com/RV96f5R.jpg", price: 3.28)
ground_beef = Item.create(description: "USDA Choice", name: "80% Lean Ground Beef", category: "Meat", img_url: "https://i.imgur.com/cpHJjSs.jpg", price: 4.39)
chicken = Item.create(description: "Our fresh, hand-trimmed chicken breast fillets are minimally processed to ensure quality and sustainability.", name: "Chicken Breast Fillets", category: "Meat", img_url: "https://i.imgur.com/gFTkiq1.jpg", price: 5.99)
hotdogs = Item.create(description: " One pack of 8 Bunsize Length Beef Franks, Made with 100% Beef.", name: "Ball Park Franks", category: "Meat", img_url: "https://i.imgur.com/Qmxi42A.jpg", price: 3.49)
sourcream = Item.create(description: "Kosher.", name: "Daisy Sour Cream", category: "Dairy", img_url: "https://i.imgur.com/yjiefhp.jpg", price: 1.77)
bacon = Item.create(description: "Hand-trimmed and smoked for a complex, savory flavor.", name: "Hormel Bacon", category: "Meat", img_url: "https://i.imgur.com/cNPh8az.jpg", price: 5.00)
mozzarella = Item.create(description: "Low-moisture, part-skim.", name: "Shredded Mozzarella Cheese", category: "Dairy", img_url: "https://i.imgur.com/u0GdkoU.jpg", price: 5.99)
milk = Item.create(description: "Wholesome and delicious, with 130 calories and 5 grams of fat per serving.", name: "Milk", category: "Dairy", img_url: "https://i.imgur.com/JdCvsTx.jpg", price: 4.49)
eggs = Item.create(description: "Hormone and antibiotic free.", name: "Eggs", category: "Dairy", img_url: "https://i.imgur.com/eO5FYqQ.jpg", price: 2.79)
cream_cheese = Item.create(description: "Rich and delicious cream cheese is made with five simple ingredients.", name: "Philadelphia Original Cream Cheese", category: "Dairy", img_url: "https://i.imgur.com/dcYqZF6.jpg", price: 1.96)
mexican_cheese = Item.create(description: "Good source of calcium.", name: "Shredded Mexican Four Cheese Blend", category: "Dairy", img_url: "https://i.imgur.com/uqi8Jzi.jpg", price: 2.19)
almond_breeze = Item.create(description: "Made with the goodness of real Blue Diamond Almonds.", name: "Almond Breeze Almondmilk", category: "Dairy", img_url: "https://i.imgur.com/1OgYyf8.jpg", price: 3.77)
sargento = Item.create(description: "Medium Cheddar Cheese perfect for appetizers, entrees, and grilled cheese sandwiches.", name: "Sargento Medium Cheddar Cheese Slices", category: "Dairy", img_url: "https://i.imgur.com/QrFc3Rc.jpg", price: 2.68)
tp = Item.create(description: "Premium bath tissue provides a comfortable clean you can count on.", name: "Quilted Northern Toilet Paper", category: "Household", img_url: "https://i.imgur.com/92lKviC.jpg", price: 8.49)
pt = Item.create(description: "Choose-A-Sheet", name: "Scott Paper Towels", category: "Household", price: 6.44, img_url: "https://i.imgur.com/379GxsI.jpg")
reynolds_wrap = Item.create(description: "A durable way to protect pans, simplify cleanup and wrap leftovers.", name: "Reynolds Wrap Aluminum Foil", category: "Household", price: 3.48, img_url: "https://i.imgur.com/cx1KtA5.jpg")
bowl_cleaner = Item.create(description: "Kills 99.9% of viruses and bacteria.", name: "Lysol Toilet Bowl Cleaner", category: "Household", price: 3.47, img_url: "https://i.imgur.com/D5S2pLh.jpg")
paper_plates = Item.create(description: "5 layers and 50% stronger than the leading store brand.", name: "Dixie White Paper Plates", category: "Household", price: 4.69, img_url: "https://i.imgur.com/8akg4YI.jpg")
windex = Item.create(description: "Perfect for cleaning glass, windows and more.", name: "Windex", category: "Household", price: 2.66, img_url: "https://i.imgur.com/jN8VNVk.jpg")
seagrams = Item.create(description: "Made with real ginger and caffeine free.", name: "Seagram's Ginger Ale", category: "Beverages", price: 5.89, img_url: "https://i.imgur.com/GkNJwIf.jpg")
diet_coke = Item.create(description: "Diet Coke is a delicious, crisp tasting, no calorie sparkling cola.", name: "Diet Coke", category: "Beverages", price: 5.57, img_url: "https://i.imgur.com/7xtBDtN.jpg")
diet_dp = Item.create(description: "Zero calories per 8 ounce serving.", name: "Diet Dr. Pepper", category: "Beverages", price: 5.28, img_url: "https://i.imgur.com/QuGpZTL.jpg")
ovc = Item.create(description: "For crips, cold taste, serve chilled at 37 degrees.", name: "Coca-Cola-Zero Orange Vanilla", category: "Beverages", price: 5.89, img_url: "https://i.imgur.com/lgaxtjg.jpg")
rootbeer = Item.create(description: "Good since 1898.", name: "Barq's Root Beer Soda", category: "Beverages", price: 5.89, img_url: "https://i.imgur.com/lquUiVL.jpg")
>>>>>>> master
